### ISSUE TITLE
Error - no layer found

### ISSUE THREAD

**Issue by giacfalk** [sandrofsousa/Segreg#2]
I keep getting the error "Error - no layer found", although I have imported a shapefile and defined its coordinate system. Why so?

**Comment by sandrofsousa** [comment]
Hi @giacfalk during the plugin load a function checks if your layer has a projected crs, in negative case this message will be shown. Only projected CRS are supported. This is due to the scipy function used to compute the distances.

I recommended checking the [Wiki](https://github.com/sandrofsousa/Segreg/wiki) page for further requisites before using the plugin.

**Comment by giacfalk** [comment]
Thank you for your prompt reply. I do not understand, since my shapefile seems to be projected (I even right clicked on it, and selected "Set layer CRS", but I keep getting the error message.

**Comment by sandrofsousa** [comment]
To make sure you have it right, you can easily check the crs by running this line in your python console at QGIS (Menu: Plugins > Python console):
`iface.activeLayer().crs().geographicFlag()`

If the result is `True` then your layer is geographic, otherwise it is projected (`False`).
